version: "3.9"

services:
    app:
        build: app1
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
networks:
    default:
        external:
            name: appteste